# Generated by Django 2.2.17 on 2021-04-01 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G4F_APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
