# Generated by Django 2.2.17 on 2021-04-05 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G4F_APP', '0005_auto_20210405_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(blank=True, default='default_profile.jpeg', upload_to='profile_images'),
        ),
    ]
